# Generated by Django 4.2.6 on 2023-11-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='b/home/priyanshi/Downloads/blank-profile-picture-973460_640.png', upload_to='profile_images'),
        ),
    ]
